### ISSUE TITLE
don't have /home/he/ub-anc/emulator/emulator

### ISSUE THREAD

**Issue by Datebasesystem** [jmodares/UB-ANC-Agent#2]
![image](https://user-images.githubusercontent.com/37975634/61207799-93b2a680-a728-11e9-9ce4-58fe02c452aa.png)
Help！ Why do I display " could not find that file or directory  ./emulator" after executing "./start_emulator.sh"?
![image](https://user-images.githubusercontent.com/37975634/61208086-2fdcad80-a729-11e9-879f-4bf1a789fd60.png)

**Comment by nmastron** [comment]
It is likely that the emulator build failed, so there is no emulator executable in ~/ub-anc/emulator/

Can you confirm that the directory ~/ub-anc/emulator/ contains the following: emulator (executable file), mav (dir), objects (dir), setup_objects.sh, start_emulator.sh.

If the build failed, you may need to go step-by-step through the build_emulator.sh script to find out where the build went wrong.

**Comment by mk959** [comment]
Hi,

I have the same issue. However, I do not have the emulator (executable file) under the directory ~/ub-anc/emulator/. I am not sure why since I followed all the steps mentioned in the "build the emulator" section. 

Is it possible that this issue is related to this part?
"Download the UB-ANC Emulator VM here and import it into your chosen virtualization software. The password to log in to the VM is UB_ANC. This VM comes with the UB-ANC Emulator already built for you in ~/ub-anc/emulator."

I downloaded the VM but I am not sure how I can import it into my chosen virtualization software. 

I would greatly appreciate it if you could help me with this issue.

**Comment by nmastron** [comment]
It appears that your build failed, which can happen for numerous reasons.

Can you please let me know the following info?

    What type of computer are you using (native windows, native mac, or native linux)?
    What version of Ubuntu are you using?
    If you are using a virtual machine, what virtualization software are you using?
    If you are using a virtual machine, how much memory are you allocating to it?
    If you are using a virtual machine, how much hard drive space are you allocating to it?

If you download the VM that I provide, then I recommend that you use VM Ware workstation player 15 (you could try 16, but I haven't tested it). You can then just click "open virtual machine" and then find the VM file that you downloaded.
